<?php
namespace Ghazy\ImportBundle\Command;

use Symfony\Bundle\FrameworkBundle\Command\ContainerAwareCommand;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;
use Ghazy\ImportBundle\Command\Proxy\YPDataLoader;
use Ghazy\ImportBundle\Command\Proxy\YPData;
use Symfony\Component\Console\Input\InputOption;

class ImportCommand extends ContainerAwareCommand
{	
	protected function configure()
	{
		$this
		->setName('ghazy:import-data')
		->addOption('no-logger', null, InputOption::VALUE_NONE, 'Do not log this operation.')
		->setDescription('Import the database')
		->setHelp(<<<EOT
The <info>ghazy:import-data</info> command import the data form the native database of 
yellow pages qatar to the database of the site generated by doctrine2
You can also optionally chose not to log this operation by using : ghazy:import-data --no-logger
EOT
        );
	}

	protected function execute(InputInterface $input, OutputInterface $output)
	{
		$dataLoader = $this->getContainer()->get('ghazy_data_loader');
		$dataLoader->loadData();
		if(!$input->getOption('no-logger'))
		{
			$logger = $this->getContainer()->get('logger');
			$infos = $dataLoader->getInfo();
			foreach ($infos as $key=>$info)
			{
				$logger->info($key.': '.$info);
			}
		}
		$output->writeln('the database is successfully imported');
	}
}